package Order::Helper::Orion::Database::Orion;
use Mojo::Base 'Daje::Utils::Sentinelsender';

use DBI;
use Try::Tiny;

has 'dbconnected' => 0;
has 'dbconnectstring';
has 'dbh';

sub DEMOLISH {
    my ($self, $in_global_destruction) = @_;

    $self->dbh->disconnect() if $self->dbh;
}

sub get_dbh{
    my $self = shift;

    my $result = 1;
    my $dbh = try {
        my $dh = DBI->connect(
            $self->dbconnectstring(),
            "Fenix", "bosab",
            {
                'RaiseError' => 1, AutoCommit => 0
            }
        );
        say "Db connection failed " unless $dh;
        $self->capture_message('','Daje-Orion', (ref $self), (caller(0))[3], $_) unless $dh;
        return $dh;
    }catch {
        $self->capture_message('','Daje-Orion', (ref $self), (caller(0))[3], $_);
        say $_;
        return ;
    };

    $result = 0 unless $dbh;
    $self->dbh($dbh);
    $self->dbconnected($result);
    return $result;
}


1;



#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

Matorit::Orion::Database::Orion


=head1 DESCRIPTION

pod generated by Pod::Autopod - keep this line to make pod updates possible ####################


=head1 REQUIRES

L<Try::Tiny>

L<DBI>

L<Mojo::Base>


=head1 METHODS

=head2 DEMOLISH

 DEMOLISH();

=head2 get_dbh

 get_dbh();


=cut



1;